name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:
  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.versions.outputs.rust-version }}
      wasmtime-latest-version: ${{ steps.versions.outputs.wasmtime-latest-version }}
      wasmtime-latest-version-major: ${{ steps.versions.outputs.wasmtime-latest-version-major }}
      wasmtime-latest-version-minor: ${{ steps.versions.outputs.wasmtime-latest-version-minor }}
      wasmtime-latest-1-version: ${{ steps.versions.outputs.wasmtime-latest-1-version }}
      wasmtime-latest-1-version-major: ${{ steps.versions.outputs.wasmtime-latest-1-version-major }}
      wasmtime-latest-1-version-minor: ${{ steps.versions.outputs.wasmtime-latest-1-version-minor }}
      wasmtime-lts-version: ${{ steps.versions.outputs.wasmtime-lts-version }}
      wasmtime-lts-version-major: ${{ steps.versions.outputs.wasmtime-lts-version-major }}
      wasmtime-lts-version-minor: ${{ steps.versions.outputs.wasmtime-lts-version-minor }}
      wasmtime-lts-1-version: ${{ steps.versions.outputs.wasmtime-lts-1-version }}
      wasmtime-lts-1-version-major: ${{ steps.versions.outputs.wasmtime-lts-1-version-major }}
      wasmtime-lts-1-version-minor: ${{ steps.versions.outputs.wasmtime-lts-1-version-minor }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Resolve versions
      id: versions
      run: |
        set -euo pipefail

        echo "rust-version=$(cargo --version | cut -d' ' -f2)" | tee -a "${GITHUB_OUTPUT}"

        # latest
        wasmtime_latest_version="$(cd versions/latest ; cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="wasmtime-cli") | .version')"
        echo "wasmtime-latest-version=${wasmtime_latest_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-latest-version-major=$(echo "${wasmtime_latest_version}" | cut -d. -f1)" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-latest-version-minor=$(echo "${wasmtime_latest_version}" | cut -d. -f1-2)" | tee -a "${GITHUB_OUTPUT}"

        # latest minus 1
        wasmtime_latest_1_version="$(cd versions/latest-1 ; cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="wasmtime-cli") | .version')"
        echo "wasmtime-latest-1-version=${wasmtime_latest_1_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-latest-1-version-major=$(echo "${wasmtime_latest_1_version}" | cut -d. -f1)" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-latest-1-version-minor=$(echo "${wasmtime_latest_1_version}" | cut -d. -f1-2)" | tee -a "${GITHUB_OUTPUT}"

        # lts
        wasmtime_lts_version="$(cd versions/lts ; cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="wasmtime-cli") | .version')"
        echo "wasmtime-lts-version=${wasmtime_lts_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-version-major=$(echo "${wasmtime_lts_version}" | cut -d. -f1)" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-version-minor=$(echo "${wasmtime_lts_version}" | cut -d. -f1-2)" | tee -a "${GITHUB_OUTPUT}"

        # lts minus 1
        wasmtime_lts_1_version="$(cd versions/lts-1 ; cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="wasmtime-cli") | .version')"
        echo "wasmtime-lts-1-version=${wasmtime_lts_1_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-1-version-major=$(echo "${wasmtime_lts_1_version}" | cut -d. -f1)" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-1-version-minor=$(echo "${wasmtime_lts_1_version}" | cut -d. -f1-2)" | tee -a "${GITHUB_OUTPUT}"
  build:
    name: Build
    permissions:
      contents: write
      packages: write
    needs: preflight
    strategy:
      fail-fast: false
      matrix:
        include:
        - wasmtime-version: ${{ needs.preflight.outputs.wasmtime-latest-version }}
          additional-tags: |
            latest
            v${{ needs.preflight.outputs.wasmtime-latest-version-major }}
            v${{ needs.preflight.outputs.wasmtime-latest-version-minor }}
          concurrency-group: ${{ needs.preflight.outputs.wasmtime-latest-version-major }}
        - wasmtime-version: ${{ needs.preflight.outputs.wasmtime-latest-1-version }}
          additional-tags: |
            v${{ needs.preflight.outputs.wasmtime-latest-1-version-major }}
            v${{ needs.preflight.outputs.wasmtime-latest-1-version-minor }}
          concurrency-group: ${{ needs.preflight.outputs.wasmtime-latest-1-version-major }}
        - wasmtime-version: ${{ needs.preflight.outputs.wasmtime-lts-version }}
          additional-tags: |
            v${{ needs.preflight.outputs.wasmtime-lts-version-major }}
            v${{ needs.preflight.outputs.wasmtime-lts-version-minor }}
          concurrency-group: ${{ needs.preflight.outputs.wasmtime-lts-version-major }}
        - wasmtime-version: ${{ needs.preflight.outputs.wasmtime-lts-1-version }}
          additional-tags: |
            v${{ needs.preflight.outputs.wasmtime-lts-1-version-major }}
            v${{ needs.preflight.outputs.wasmtime-lts-1-version-minor }}
          concurrency-group: ${{ needs.preflight.outputs.wasmtime-lts-1-version-major }}
    uses: ./.github/workflows/publish.yaml
    with:
      rust-version: "${{ needs.preflight.outputs.rust-version }}"
      wasmtime-version: "${{ matrix.wasmtime-version }}"
      publish: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      force: false
      additional-tags: "${{ matrix.additional-tags }}"
      concurrency-group: "${{ matrix.concurrency-group }}"
    secrets: inherit

  done:
    # used as a non-matrix job for protected branches
    name: Done
    needs: build
    if: always() && (needs.build.result == 'success' || needs.build.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
    - run: echo "That's all folks"
