name: Manual publish

on:
  workflow_dispatch:
    inputs:
      wasmtime-crate:
        description: wasmtime crate version to build
        type: string
      wasmtime-git-ref:
        description: wasmtime git ref to build ('refs/tag/{tag}', 'refs/heads/{branch}')
        required: true
        type: string
      repository:
        description: image repository to publish into
        type: string
      tag:
        description: primary image tag to publish
        required: true
        type: string
      additional-tags:
        description: white-space delimited set of additional tags to add to the published image
        type: string
      force:
        description: force overwriting an existing image
        type: boolean
        default: false
      rust-version:
        description: rust version to build
        type: string

jobs:

  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.versions.outputs.rust-version }}
      wasmtime-git-sha: ${{ steps.versions.outputs.wasmtime-git-sha }}
      additional-tags: ${{ steps.versions.outputs.additional-tags }}
    steps:
    - uses: actions/checkout@v6
    - name: Resolve versions
      id: versions
      run: |
        set -euo pipefail

        echo "rust-version=${{ inputs.rust-version || '$(yq -r ''.toolchain.channel'' rust-toolchain.toml)' }}" | tee -a "${GITHUB_OUTPUT}"

        wasmtime_git_sha="$(gh api "repos/bytecodealliance/wasmtime/commits/${{ inputs.wasmtime-git-ref }}" --template '{{.sha}}')"
        echo "wasmtime-git-sha=${wasmtime_git_sha}" | tee -a "${GITHUB_OUTPUT}"

        # convert space delimited to new-line delimited
        echo 'additional-tags<<EOF' | tee -a "${GITHUB_OUTPUT}"
        echo "${{ inputs.additional-tags }}" | perl -pe 's/\s+/\n/g' | tee -a "${GITHUB_OUTPUT}"
        echo 'EOF' | tee -a "${GITHUB_OUTPUT}"
      env:
        GH_TOKEN: ${{ github.token }}

  publish:
    name: Publish
    permissions:
      packages: write
    needs: preflight
    uses: ./.github/workflows/publish.yaml
    with:
      rust-version: "${{ needs.preflight.outputs.rust-version }}"
      wasmtime-crate: "${{ inputs.wasmtime-crate }}"
      wasmtime-git-sha: "${{ needs.preflight.outputs.wasmtime-git-sha }}"
      repository: "${{ inputs.repository }}"
      tag: "${{ inputs.tag }}"
      additional-tags: "${{ needs.preflight.outputs.additional-tags }}"
      force: ${{ inputs.force }}
    secrets: inherit
