name: Manual publish

on:
  workflow_dispatch:
    inputs:
      wasmtime-version:
        description: wasmtime version to build
        required: true
        type: string
      wasmtime-source:
        description: wasmtime source. 'crate' or 'git'
        required: true
        type: choice
        default: crate
        options:
        - crate
        - git
      repository:
        description: image repository to publish into
        type: string
      tag:
        description: primary image tag to publish
        required: true
        type: string
      additional-tags:
        description: white-space delimited set of additional tags to add to the published image
        type: string
      force:
        description: force overwriting an existing image
        type: boolean
        default: false

jobs:

  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.versions.outputs.rust-version }}
      additional-tags: ${{ steps.versions.outputs.additional-tags }}
    steps:
    - uses: actions/checkout@v6
    - name: Resolve versions
      id: versions
      run: |
        set -euo pipefail

        echo "rust-version=$(yq -r '.toolchain.channel' rust-toolchain.toml)" | tee -a "${GITHUB_OUTPUT}"
        # convert space delimited to new-line delimited
        echo 'additional-tags<<EOF' >> $GITHUB_OUTPUT
        echo $(echo "${{ inputs.additional-tags }}" | perl -pe 's/\s+/\n/g') >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

  publish:
    name: Publish wasmtime image
    needs: preflight
    uses: ./.github/workflows/publish.yaml
    with:
      rust-version: "${{ needs.preflight.outputs.rust-version }}"
      wasmtime-source: "${{ inputs.wasmtime-source }}"
      wasmtime-version: "${{ inputs.wasmtime-version }}"
      repository: "${{ inputs.repository || format('ghcr.io/{0}', github.repository) }}"
      tag: "${{ inputs.tag }}"
      additional-tags: "${{ needs.preflight.outputs.additional-tags }}"
      force: ${{ inputs.force }}
    secrets: inherit
