name: Publish

on:
  workflow_call:
    inputs:
      wasmtime-version:
        description: wasmtime version to build
        required: true
        type: string
      wasmtime-source:
        description: wasmtime source. 'crate' or 'git'
        type: string
        default: crate
      rust-version:
        description: rust version to build
        required: true
        type: string
      repository:
        description: nested image repository to publish into
        type: string
        default: ""
      tag:
        description: primary image tag to publish
        required: true
        type: string
      additional-tags:
        description: new line delimited set of additional tags to add to the published image
        type: string
      publish:
        description: publish built image
        type: boolean
        default: true
      force:
        description: force overwriting an existing image
        type: boolean
        default: false

concurrency:
  group: ${{ case(inputs.publish, inputs.tag, format('run-{0}-v{1}', github.run_id, inputs.tag)) }}
  queue: max

env:
  image: "${{
      case(inputs.repository == '',
        format('ghcr.io/{0}:{1}', github.repository, inputs.tag),
        format('ghcr.io/{0}/{1}:{2}', github.repository, inputs.repository, inputs.tag)
      )
    }}"

jobs:

  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    outputs:
      existing-digest: ${{ steps.existing.outputs.digest }}
    steps:
    - uses: actions/checkout@v6
    - name: Install crane
      uses: reconcilerio/install-crane-action@v1
    - name: Check for existing image
      id: existing
      run: |
        set -euo pipefail

        digest="$(crane digest "${{ env.image }}" || echo -n '')"
        echo "digest=${digest}" | tee -a "${GITHUB_OUTPUT}"

  build:
    name: Build
    needs: preflight
    if: ${{ inputs.force || ! needs.preflight.outputs.existing-digest }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-24.04
          arch: amd64
        - os: ubuntu-24.04-arm
          arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: |
        set -euo pipefail

        docker buildx create \
          --name container \
          --driver=docker-container \
          default

        docker buildx build \
          --builder container \
          --output type=oci,dest="./wasmtime-${{ inputs.wasmtime-version }}-${{ matrix.arch }}.tar" \
          --platform "linux/${{ matrix.arch }}" \
          --build-arg "rust=${{ inputs.rust-version }}" \
          --build-arg "wasmtime_source=${{ inputs.wasmtime-source }}" \
          --build-arg "wasmtime=${{ inputs.wasmtime-version }}" \
          --provenance false \
          --sbom=false \
          .

        mkdir "wasmtime-${{ inputs.wasmtime-version }}-${{ matrix.arch }}"
        tar -xvf "wasmtime-${{ inputs.wasmtime-version }}-${{ matrix.arch }}.tar" -C "wasmtime-${{ inputs.wasmtime-version }}-${{ matrix.arch }}"
    - uses: actions/upload-artifact@v7
      with:
        name: "wasmtime-${{ inputs.wasmtime-version }}-${{ matrix.arch }}"
        path: "wasmtime-${{ inputs.wasmtime-version }}-${{ matrix.arch }}"
        retention-days: 7

  assemble:
    name: Assemble
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install crane
      uses: reconcilerio/install-crane-action@v1
    - name: OCI registry
      uses: reconcilerio/registry@v1
    - name: Download staged image (amd64)
      uses: actions/download-artifact@v8
      with:
        name: "wasmtime-${{ inputs.wasmtime-version }}-amd64"
        path: "wasmtime-${{ inputs.wasmtime-version }}-amd64"
    - name: Download staged image (arm64)
      uses: actions/download-artifact@v8
      with:
        name: "wasmtime-${{ inputs.wasmtime-version }}-arm64"
        path: "wasmtime-${{ inputs.wasmtime-version }}-arm64"
    - name: Assemble
      run: |
        set -euo pipefail

        crane push \
          "wasmtime-${{ inputs.wasmtime-version }}-amd64" \
          registry.local/wasmtime:amd64

        crane push \
          "wasmtime-${{ inputs.wasmtime-version }}-arm64" \
          registry.local/wasmtime:arm64

        crane index append \
          -m registry.local/wasmtime:amd64 \
          -m registry.local/wasmtime:arm64 \
          -t registry.local/wasmtime

        crane pull --format oci \
          registry.local/wasmtime \
          "wasmtime-${{ inputs.wasmtime-version }}"
    - uses: actions/upload-artifact@v7
      with:
        name: "wasmtime-${{ inputs.wasmtime-version }}"
        path: "wasmtime-${{ inputs.wasmtime-version }}"
        retention-days: 7

  test:
    name: Test wasmtime image
    needs: assemble
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-24.04
        - os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Install crane
      uses: reconcilerio/install-crane-action@v1
    - name: OCI registry
      uses: reconcilerio/registry@v1
    - name: Download staged image
      uses: actions/download-artifact@v8
      with:
        name: "wasmtime-${{ inputs.wasmtime-version }}"
        path: "wasmtime-${{ inputs.wasmtime-version }}"
    - name: Relocate image
      run: |
        crane push \
          "wasmtime-${{ inputs.wasmtime-version }}" \
          registry.local/wasmtime
    # TODO test image
    - name: Run container
      run: docker run --rm registry.local/wasmtime
    - name: Check expected images in index
      run: |
        set -euo pipefail

        listing=$(crane index list registry.local/wasmtime)
        echo "${listing}"

        echo "${listing}" | grep -q linux/amd64
        echo "${listing}" | grep -q linux/arm64

  publish:
    name: Publish
    needs: test
    if: inputs.publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v6
    - name: Install crane
      uses: reconcilerio/install-crane-action@v1
    - name: Download staged image
      uses: actions/download-artifact@v8
      with:
        name: "wasmtime-${{ inputs.wasmtime-version }}"
        path: "wasmtime-${{ inputs.wasmtime-version }}"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push
      run: |
        crane push \
          "wasmtime-${{ inputs.wasmtime-version }}" \
          "${{ env.image }}"
    - name: Additional tags
      if: inputs.additional-tags
      run: |
        set -euo pipefail

        additional_tags="$(echo "${{ inputs.additional-tags }}" | awk '{$1=$1};1' | grep -v -e "^$")"

        while IFS= read -r tag; do
          crane tag \
            "${{ env.image }}" \
            "${tag}"
        done <<< "${additional_tags}"
