name: Pull request

on:
  pull_request: {}

jobs:

  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      rust-version: ${{ steps.versions.outputs.rust-version }}
      wasmtime-stable-changed: ${{ steps.filter.outputs.wasmtime-stable }}
      wasmtime-stable-git-sha: ${{ steps.versions.outputs.wasmtime-stable-git-sha }}
      wasmtime-stable-version: ${{ steps.versions.outputs.wasmtime-stable-version }}
      wasmtime-stable-1-changed: ${{ steps.filter.outputs.wasmtime-stable-1 }}
      wasmtime-stable-1-git-sha: ${{ steps.versions.outputs.wasmtime-stable-1-git-sha }}
      wasmtime-stable-1-version: ${{ steps.versions.outputs.wasmtime-stable-1-version }}
      wasmtime-lts-changed: ${{ steps.filter.outputs.wasmtime-lts }}
      wasmtime-lts-git-sha: ${{ steps.versions.outputs.wasmtime-lts-git-sha }}
      wasmtime-lts-version: ${{ steps.versions.outputs.wasmtime-lts-version }}
      wasmtime-lts-1-changed: ${{ steps.filter.outputs.wasmtime-lts-1 }}
      wasmtime-lts-1-git-sha: ${{ steps.versions.outputs.wasmtime-lts-1-git-sha }}
      wasmtime-lts-1-version: ${{ steps.versions.outputs.wasmtime-lts-1-version }}
      wasmtime-dev-git-sha: ${{ steps.versions.outputs.wasmtime-dev-git-sha }}
      common-changed: ${{ steps.filter.outputs.common }}
    steps:
    - uses: actions/checkout@v6
    - uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          common:
          - '.github/**'
          - 'Dockerfile'
          - 'rust-toolchain.toml'
          - 'versions/cargo-auditable/**'
          wasmtime-stable:
          - 'versions/stable/**'
          wasmtime-stable-1:
          - 'versions/stable-1/**'
          wasmtime-lts:
          - 'versions/lts/**'
          wasmtime-lts-1:
          - 'versions/lts-1/**'
    - name: Resolve versions
      id: versions
      run: |
        set -euo pipefail

        echo "rust-version=$(yq -r '.toolchain.channel' rust-toolchain.toml)" | tee -a "${GITHUB_OUTPUT}"

        # stable
        wasmtime_stable_version="$(cd versions/stable ; yq -p toml -oj -r '.package[] | select(.name == "wasmtime-cli") | .version' Cargo.lock)"
        wasmtime_stable_git_sha="$(gh api "repos/bytecodealliance/wasmtime/commits/refs/tags/v${wasmtime_stable_version}" --template '{{.sha}}')"
        echo "wasmtime-stable-version=${wasmtime_stable_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-stable-git-sha=${wasmtime_stable_git_sha}" | tee -a "${GITHUB_OUTPUT}"

        # stable, minus 1
        wasmtime_stable_1_version="$(cd versions/stable-1 ; yq -p toml -oj -r '.package[] | select(.name == "wasmtime-cli") | .version' Cargo.lock)"
        wasmtime_stable_1_git_sha="$(gh api "repos/bytecodealliance/wasmtime/commits/refs/tags/v${wasmtime_stable_1_version}" --template '{{.sha}}')"
        echo "wasmtime-stable-1-version=${wasmtime_stable_1_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-stable-1-git-sha=${wasmtime_stable_1_git_sha}" | tee -a "${GITHUB_OUTPUT}"

        # lts
        wasmtime_lts_version="$(cd versions/lts ; yq -p toml -oj -r '.package[] | select(.name == "wasmtime-cli") | .version' Cargo.lock)"
        wasmtime_lts_git_sha="$(gh api "repos/bytecodealliance/wasmtime/commits/refs/tags/v${wasmtime_lts_version}" --template '{{.sha}}')"
        echo "wasmtime-lts-version=${wasmtime_lts_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-git-sha=${wasmtime_lts_git_sha}" | tee -a "${GITHUB_OUTPUT}"

        # lts, minus 1
        wasmtime_lts_1_version="$(cd versions/lts-1 ; yq -p toml -oj -r '.package[] | select(.name == "wasmtime-cli") | .version' Cargo.lock)"
        wasmtime_lts_1_git_sha="$(gh api "repos/bytecodealliance/wasmtime/commits/refs/tags/v${wasmtime_lts_1_version}" --template '{{.sha}}')"
        echo "wasmtime-lts-1-version=${wasmtime_lts_1_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-1-git-sha=${wasmtime_lts_1_git_sha}" | tee -a "${GITHUB_OUTPUT}"

        # dev
        wasmtime_dev_git_sha="$(gh api "repos/bytecodealliance/wasmtime/commits/refs/tags/dev" --template '{{.sha}}')"
        echo "wasmtime-dev-git-sha=${wasmtime_dev_git_sha}" | tee -a "${GITHUB_OUTPUT}"
      env:
        GH_TOKEN: ${{ github.token }}

  publish:
    name: Publish
    permissions:
      # called workflow requires write even though it's never used from here
      packages: write
    needs: preflight
    strategy:
      fail-fast: false
      matrix:
        include:
        - tag: v${{ needs.preflight.outputs.wasmtime-stable-version }}
          wasmtime-crate: ${{ needs.preflight.outputs.wasmtime-stable-version }}
          wasmtime-git-sha: ${{ needs.preflight.outputs.wasmtime-stable-git-sha }}
          force: ${{ needs.preflight.outputs.wasmtime-stable-changed == 'true' || needs.preflight.outputs.common-changed == 'true' }}
        - tag: v${{ needs.preflight.outputs.wasmtime-stable-1-version }}
          wasmtime-crate: ${{ needs.preflight.outputs.wasmtime-stable-1-version }}
          wasmtime-git-sha: ${{ needs.preflight.outputs.wasmtime-stable-1-git-sha }}
          force: ${{ needs.preflight.outputs.wasmtime-stable-1-changed == 'true' || needs.preflight.outputs.common-changed == 'true' }}
        - tag: v${{ needs.preflight.outputs.wasmtime-lts-version }}
          wasmtime-crate: ${{ needs.preflight.outputs.wasmtime-lts-version }}
          wasmtime-git-sha: ${{ needs.preflight.outputs.wasmtime-lts-git-sha }}
          force: ${{ needs.preflight.outputs.wasmtime-lts-changed == 'true' || needs.preflight.outputs.common-changed == 'true' }}
        - tag: v${{ needs.preflight.outputs.wasmtime-lts-1-version }}
          wasmtime-crate: ${{ needs.preflight.outputs.wasmtime-lts-1-version }}
          wasmtime-git-sha: ${{ needs.preflight.outputs.wasmtime-lts-1-git-sha }}
          force: ${{ needs.preflight.outputs.wasmtime-lts-1-changed == 'true' || needs.preflight.outputs.common-changed == 'true' }}
        - tag: dev-${{ needs.preflight.outputs.wasmtime-dev-git-sha }}
          wasmtime-crate: ''
          wasmtime-git-sha: ${{ needs.preflight.outputs.wasmtime-dev-git-sha }}
          force: ${{ needs.preflight.outputs.common-changed == 'true' }}
    uses: ./.github/workflows/publish.yaml
    with:
      rust-version: "${{ needs.preflight.outputs.rust-version }}"
      wasmtime-crate: "${{ matrix.wasmtime-crate }}"
      wasmtime-git-sha: "${{ matrix.wasmtime-git-sha }}"
      tag: "${{ matrix.tag }}"
      publish: false
      force: ${{ matrix.force }}
    secrets: inherit

  done:
    # used as a non-matrix job for protected branches
    name: Done
    needs: publish
    if: always() && (needs.publish.result == 'success' || needs.publish.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
    - run: echo "That's all folks"
