name: Push

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'

jobs:

  preflight:
    name: Preflight
    runs-on: ubuntu-latest
    outputs:
      rust-version: ${{ steps.versions.outputs.rust-version }}
      wasmtime-latest-version: ${{ steps.versions.outputs.wasmtime-latest-version }}
      wasmtime-latest-version-major: ${{ steps.versions.outputs.wasmtime-latest-version-major }}
      wasmtime-latest-version-minor: ${{ steps.versions.outputs.wasmtime-latest-version-minor }}
      wasmtime-latest-1-version: ${{ steps.versions.outputs.wasmtime-latest-1-version }}
      wasmtime-latest-1-version-major: ${{ steps.versions.outputs.wasmtime-latest-1-version-major }}
      wasmtime-latest-1-version-minor: ${{ steps.versions.outputs.wasmtime-latest-1-version-minor }}
      wasmtime-lts-version: ${{ steps.versions.outputs.wasmtime-lts-version }}
      wasmtime-lts-version-major: ${{ steps.versions.outputs.wasmtime-lts-version-major }}
      wasmtime-lts-version-minor: ${{ steps.versions.outputs.wasmtime-lts-version-minor }}
      wasmtime-lts-1-version: ${{ steps.versions.outputs.wasmtime-lts-1-version }}
      wasmtime-lts-1-version-major: ${{ steps.versions.outputs.wasmtime-lts-1-version-major }}
      wasmtime-lts-1-version-minor: ${{ steps.versions.outputs.wasmtime-lts-1-version-minor }}
    steps:
    - uses: actions/checkout@v6
    - name: Resolve versions
      id: versions
      run: |
        set -euo pipefail

        echo "rust-version=$(yq -r '.toolchain.channel' rust-toolchain.toml)" | tee -a "${GITHUB_OUTPUT}"

        # latest
        wasmtime_latest_version="$(cd versions/latest ; yq -p toml -oj -r '.package[] | select(.name == "wasmtime-cli") | .version' Cargo.lock)"
        echo "wasmtime-latest-version=${wasmtime_latest_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-latest-version-major=$(echo "${wasmtime_latest_version}" | cut -d. -f1)" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-latest-version-minor=$(echo "${wasmtime_latest_version}" | cut -d. -f1-2)" | tee -a "${GITHUB_OUTPUT}"

        # latest minus 1
        wasmtime_latest_1_version="$(cd versions/latest-1 ; yq -p toml -oj -r '.package[] | select(.name == "wasmtime-cli") | .version' Cargo.lock)"
        echo "wasmtime-latest-1-version=${wasmtime_latest_1_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-latest-1-version-major=$(echo "${wasmtime_latest_1_version}" | cut -d. -f1)" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-latest-1-version-minor=$(echo "${wasmtime_latest_1_version}" | cut -d. -f1-2)" | tee -a "${GITHUB_OUTPUT}"

        # lts
        wasmtime_lts_version="$(cd versions/lts ; yq -p toml -oj -r '.package[] | select(.name == "wasmtime-cli") | .version' Cargo.lock)"
        echo "wasmtime-lts-version=${wasmtime_lts_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-version-major=$(echo "${wasmtime_lts_version}" | cut -d. -f1)" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-version-minor=$(echo "${wasmtime_lts_version}" | cut -d. -f1-2)" | tee -a "${GITHUB_OUTPUT}"

        # lts minus 1
        wasmtime_lts_1_version="$(cd versions/lts-1 ; yq -p toml -oj -r '.package[] | select(.name == "wasmtime-cli") | .version' Cargo.lock)"
        echo "wasmtime-lts-1-version=${wasmtime_lts_1_version}" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-1-version-major=$(echo "${wasmtime_lts_1_version}" | cut -d. -f1)" | tee -a "${GITHUB_OUTPUT}"
        echo "wasmtime-lts-1-version-minor=$(echo "${wasmtime_lts_1_version}" | cut -d. -f1-2)" | tee -a "${GITHUB_OUTPUT}"

  publish:
    name: Publish
    permissions:
      packages: write
    needs: preflight
    strategy:
      fail-fast: false
      matrix:
        include:
        - wasmtime-version: ${{ needs.preflight.outputs.wasmtime-latest-version }}
          tag: v${{ needs.preflight.outputs.wasmtime-latest-version }}
          additional-tags: |
            v${{ needs.preflight.outputs.wasmtime-latest-version-minor }}
            v${{ needs.preflight.outputs.wasmtime-latest-version-major }}
            latest
        - wasmtime-version: ${{ needs.preflight.outputs.wasmtime-latest-1-version }}
          tag: v${{ needs.preflight.outputs.wasmtime-latest-1-version }}
          additional-tags: |
            v${{ needs.preflight.outputs.wasmtime-latest-1-version-minor }}
            v${{ needs.preflight.outputs.wasmtime-latest-1-version-major }}
            latest-1
        - wasmtime-version: ${{ needs.preflight.outputs.wasmtime-lts-version }}
          tag: v${{ needs.preflight.outputs.wasmtime-lts-version }}
          additional-tags: |
            v${{ needs.preflight.outputs.wasmtime-lts-version-major }}
            v${{ needs.preflight.outputs.wasmtime-lts-version-minor }}
            lts
        - wasmtime-version: ${{ needs.preflight.outputs.wasmtime-lts-1-version }}
          tag: v${{ needs.preflight.outputs.wasmtime-lts-1-version }}  
          additional-tags: |
            v${{ needs.preflight.outputs.wasmtime-lts-1-version-minor }}
            v${{ needs.preflight.outputs.wasmtime-lts-1-version-major }}
            lts-1
    uses: ./.github/workflows/publish.yaml
    with:
      rust-version: "${{ needs.preflight.outputs.rust-version }}"
      wasmtime-version: "${{ matrix.wasmtime-version }}"
      tag: "${{ matrix.tag }}"
      additional-tags: "${{ matrix.additional-tags }}"
      publish: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit

  done:
    # used as a non-matrix job for protected branches
    name: Done
    needs: publish
    if: always() && (needs.publish.result == 'success' || needs.publish.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
    - run: echo "That's all folks"
